### ISSUE TITLE
Incompatible with Aurora's Decorations

### ISSUE THREAD

**Issue by Sunconure11** [MehVahdJukaar/Moonlight#50]
https://pastebin.com/YWqPPFSq

Also, you might want to check this issue as well, as this crash manifested after disabling Wired Redstone: https://github.com/Kneelawk/WiredRedstone/issues/21

**Comment by MehVahdJukaar** [comment]
problem is not on my end. Aurora's Deco does something very similar to what I do so I know what the issue is. it's basically trying to register a shelf using the charred wood type and to do so it copies the block properties of the block. However this isnt safe as those properties include some lambdas for stuff like light level which assume the given blockstate is the one they expect. In this case its trying to register a charred wood shelf with the charred wood type who gets its light levle by chekcing its blockstaes, problem is that that shelf block has no such blockstate so it crashes. Those properties should then not be copied to have this work properly (Issue is with Immersive Weathering in particular btw but could happen with any other mod)
You should report this on Aurora's deco issue page

**Comment by Sunconure11** [comment]
I had reported it. However, due to PC issues, I can’t test further.

https://github.com/LambdAurora/AurorasDecorations/issues/28
