### ISSUE TITLE
Modrinth page is outdated and does not reflect the current state of the mod

### ISSUE THREAD

**Issue by hibiii** [MehVahdJukaar/Moonlight#53]
The CurseForge page about Moonlight shows the latest version is 2.1.3 available for both Fabric and Forge 19.2, but the Modrinth page shows only 1.9.0 for Forge 16.5.

**Comment by MehVahdJukaar** [comment]
I dont really plan to update 2 files across 2 websites all the time. I put it there just because once somebody bugged me to do it. I'm not sayin that modrinth is bad or anything just that keeping up with it isnt worth it for me at least right now. Having said that I uploaded the most recent version there but dont expect frequent updates
